language: generic
sudo: required
services:
  - docker
dist: trusty

before_script:
  - echo $TRAVIS_BUILD_DIR
  - docker --version
  - make build-docker
  - make start-container

script:
  - make build-debug
  - make test

